# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: npmjs-sample-variables

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/heads/feature/npm-semantic-release

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: blip-toolkit
    type: javascript
    to: semantic-release
    npmCmds:
    - npm install
    - npm prune && npm install -g codecov
    - npm run test:show-coverage
    - npm run test:upload-coverage
    - codecov
    - npm run build
